export const genreList = [
    "Fiction",
    "Classic",
    "Dystopian",
    "Science Fiction",
    "Romance",
    "Adventure",
    "Fantasy",
    "Coming-of-age",
    "Magical Realism",
    "Literary Fiction",
    "Historical Fiction",
    "Epic",
    "Mythology",
    "Poetry",
    "Philosophical Fiction",
    "Gothic",
    "Satire",
    "Children's Literature",
    "Fable",
    "War",
    "Feminist Fiction",
    "Mystery",
    "Absurdist Fiction",
    "Existential"
  ]